In [1]:
import pandas as pd
import glob

In [38]:
# Carica il CSV in un DataFrame
df = pd.read_csv('dataset/2009.csv')

In [29]:
#CREA UN DF CON TUTTI I CSV

# Specifica il percorso alla cartella che contiene i file CSV
percorso = 'dataset/*.csv'

# Usa glob per trovare tutti i file CSV nella cartella
file_csv = glob.glob(percorso)

# Leggi e unisci tutti i file in un unico DataFrame
df = pd.concat([pd.read_csv(file) for file in file_csv], ignore_index=True)

In [10]:
df.head()

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2009-01-01,XE,1204,DCA,EWR,1100,1058.0,-2.0,18.0,1116.0,...,0.0,62.0,68.0,42.0,199.0,NaN,NaN,NaN,NaN,NaN
1,2009-01-01,XE,1206,EWR,IAD,1510,1509.0,-1.0,28.0,1537.0,...,0.0,82.0,75.0,43.0,213.0,NaN,NaN,NaN,NaN,NaN
2,2009-01-01,XE,1207,EWR,DCA,1100,1059.0,-1.0,20.0,1119.0,...,0.0,70.0,62.0,36.0,199.0,NaN,NaN,NaN,NaN,NaN
3,2009-01-01,XE,1208,DCA,EWR,1240,1249.0,9.0,10.0,1259.0,...,0.0,77.0,56.0,37.0,199.0,NaN,NaN,NaN,NaN,NaN
4,2009-01-01,XE,1209,IAD,EWR,1715,1705.0,-10.0,24.0,1729.0,...,0.0,105.0,77.0,40.0,213.0,NaN,NaN,NaN,NaN,NaN

In [36]:
print(df.columns)
print(len(df.columns))

Index(['FL_DATE', 'OP_CARRIER', 'OP_CARRIER_FL_NUM', 'ORIGIN', 'DEST',
       'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF',
       'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY',
       'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME',
       'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'CARRIER_DELAY',
       'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY',
       'Unnamed: 27'],
      dtype='object')
28

# ETL

In [3]:
# Per ogni colonna  calcola la percentuale di NaN e non NaN
for col in df.columns:
    nan_percent = df[col].isna().mean() * 100  # Percentuale di NaN
    non_nan_percent = 100 - nan_percent  # Percentuale di non NaN
    print(f"Colonna: {col}")
    print(f"Percentuale di NaN: {nan_percent:.2f}%")
    print(f"Percentuale di non NaN: {non_nan_percent:.2f}%")
    print("-" * 40)

Colonna: FL_DATE
Percentuale di NaN: 0.00%
Percentuale di non NaN: 100.00%
----------------------------------------
Colonna: OP_CARRIER
Percentuale di NaN: 0.00%
Percentuale di non NaN: 100.00%
----------------------------------------
Colonna: OP_CARRIER_FL_NUM
Percentuale di NaN: 0.00%
Percentuale di non NaN: 100.00%
----------------------------------------
Colonna: ORIGIN
Percentuale di NaN: 0.00%
Percentuale di non NaN: 100.00%
----------------------------------------
Colonna: DEST
Percentuale di NaN: 0.00%
Percentuale di non NaN: 100.00%
----------------------------------------
Colonna: CRS_DEP_TIME
Percentuale di NaN: 0.00%
Percentuale di non NaN: 100.00%
----------------------------------------
Colonna: DEP_TIME
Percentuale di NaN: 1.29%
Percentuale di non NaN: 98.71%
----------------------------------------
Colonna: DEP_DELAY
Percentuale di NaN: 1.29%
Percentuale di non NaN: 98.71%
----------------------------------------
Colonna: TAXI_OUT
Percentuale di NaN: 1.33%
Percentuale di non NaN: 98.67%
----------------------------------------
Colonna: WHEELS_OFF
Percentuale di NaN: 1.33%
Percentuale di non NaN: 98.67%
----------------------------------------
Colonna: WHEELS_ON
Percentuale di NaN: 1.39%
Percentuale di non NaN: 98.61%
----------------------------------------
Colonna: TAXI_IN
Percentuale di NaN: 1.39%
Percentuale di non NaN: 98.61%
----------------------------------------
Colonna: CRS_ARR_TIME
Percentuale di NaN: 0.00%
Percentuale di non NaN: 100.00%
----------------------------------------
Colonna: ARR_TIME
Percentuale di NaN: 1.39%
Percentuale di non NaN: 98.61%
----------------------------------------
Colonna: ARR_DELAY
Percentuale di NaN: 1.59%
Percentuale di non NaN: 98.41%
----------------------------------------
Colonna: CANCELLED
Percentuale di NaN: 0.00%
Percentuale di non NaN: 100.00%
----------------------------------------
Colonna: CANCELLATION_CODE
Percentuale di NaN: 98.65%
Percentuale di non NaN: 1.35%
----------------------------------------
Colonna: DIVERTED
Percentuale di NaN: 0.00%
Percentuale di non NaN: 100.00%
----------------------------------------
Colonna: CRS_ELAPSED_TIME
Percentuale di NaN: 0.00%
Percentuale di non NaN: 100.00%
----------------------------------------
Colonna: ACTUAL_ELAPSED_TIME
Percentuale di NaN: 1.59%
Percentuale di non NaN: 98.41%
----------------------------------------
Colonna: AIR_TIME
Percentuale di NaN: 1.59%
Percentuale di non NaN: 98.41%
----------------------------------------
Colonna: DISTANCE
Percentuale di NaN: 0.00%
Percentuale di non NaN: 100.00%
----------------------------------------
Colonna: CARRIER_DELAY
Percentuale di NaN: 81.79%
Percentuale di non NaN: 18.21%
----------------------------------------
Colonna: WEATHER_DELAY
Percentuale di NaN: 81.79%
Percentuale di non NaN: 18.21%
----------------------------------------
Colonna: NAS_DELAY
Percentuale di NaN: 81.79%
Percentuale di non NaN: 18.21%
----------------------------------------
Colonna: SECURITY_DELAY
Percentuale di NaN: 81.79%
Percentuale di non NaN: 18.21%
----------------------------------------
Colonna: LATE_AIRCRAFT_DELAY
Percentuale di NaN: 81.79%
Percentuale di non NaN: 18.21%
----------------------------------------
Colonna: Unnamed: 27
Percentuale di NaN: 100.00%
Percentuale di non NaN: 0.00%
----------------------------------------

In [29]:
# Calcola la percentuale di NaN per ciascuna colonna
soglia_nan = 0.5  # soglia del 50% di valori NaN
colonne_more_05_nan = df.columns[df.isna().mean() > soglia_nan]

# Per ogni colonna che ha piÃ¹ del 50% di NaN, calcola la percentuale di NaN e non NaN
for col in colonne_more_05_nan:
    nan_percent = df[col].isna().mean() * 100  # Percentuale di NaN
    non_nan_percent = 100 - nan_percent  # Percentuale di non NaN
    print(f"Colonna: {col}")
    print(f"Percentuale di NaN: {nan_percent:.2f}%")
    print(f"Percentuale di non NaN: {non_nan_percent:.2f}%")
    print("-" * 40)

Colonna: CANCELLATION_CODE
Percentuale di NaN: 98.65%
Percentuale di non NaN: 1.35%
----------------------------------------
Colonna: CARRIER_DELAY
Percentuale di NaN: 81.79%
Percentuale di non NaN: 18.21%
----------------------------------------
Colonna: WEATHER_DELAY
Percentuale di NaN: 81.79%
Percentuale di non NaN: 18.21%
----------------------------------------
Colonna: NAS_DELAY
Percentuale di NaN: 81.79%
Percentuale di non NaN: 18.21%
----------------------------------------
Colonna: SECURITY_DELAY
Percentuale di NaN: 81.79%
Percentuale di non NaN: 18.21%
----------------------------------------
Colonna: LATE_AIRCRAFT_DELAY
Percentuale di NaN: 81.79%
Percentuale di non NaN: 18.21%
----------------------------------------
Colonna: Unnamed: 27
Percentuale di NaN: 100.00%
Percentuale di non NaN: 0.00%
----------------------------------------

### Analisi delay

In [64]:
# Lista delle colonne *_DELAY che ti interessano (quelle nel tuo output)
delay_columns = [
    'CARRIER_DELAY',
    'WEATHER_DELAY',
    'NAS_DELAY',
    'SECURITY_DELAY',
    'LATE_AIRCRAFT_DELAY'
]

# Ci sono dei valori di Arr_Delay che hanno i valori di delay specifici settati a NAN
# Filtra le righe che hanno almeno un valore x_delay non NaN
delay_rows_non_nan = df.dropna(subset=delay_columns)

# Verifica se ci sono righe dove almeno un *_DELAY Ã¨ non NaN e altre colonne sono NaN
mask_non_nan = delay_rows_non_nan[delay_columns].notna().all(axis=1)  # Righe con tutti i *_DELAY non NaN

print("Se un delay specifico Ã¨ non nan allora tutti gli altri pure non lo saranno:" + str(mask_non_nan.all()))

# Trova le righe che non soddisfano il criterio
inconsistent_rows = delay_rows_non_nan[~mask_non_nan]

# Stampa le righe con inconsistenze
if not inconsistent_rows.empty:
    # nel caso un tipo di delay specifico Ã¨ NaN anche tutti gli altri tipi specifici devono essere NaN
    for index in inconsistent_rows.index:
        print(f"Riga {index} ha NaN in una colonna *_DELAY mentre altre sono non NaN.")
else:
    # Alcuni valori di ARR_DELAY sono dati dalla somma degli altri valori delay
    condition = (delay_rows_non_nan[delay_columns].sum(axis=1) == delay_rows_non_nan['ARR_DELAY'])
    df_invalid = delay_rows_non_nan[~condition]

    if df_invalid.empty:
        print("Non ci sono inconsistenze nelle colonne di DELAY con i valori di DELAY specifi non NaN.")
        print("I valori di ARR_DELAY sono dati dalla somma degli altri valori delay specifi nel caso questi fossero non NaN")
    else:
        print("Ci sono inconsistenze")
        print(df_invalid[['ARR_DELAY'] + delay_columns])



delay_rows_non_nan[['ARR_DELAY'] + delay_columns ]

Se un delay specifico Ã¨ non nan allora tutti gli altri pure non lo saranno:True
Non ci sono inconsistenze nelle colonne di DELAY con i valori di DELAY specifi non NaN.
I valori di ARR_DELAY sono dati dalla somma degli altri valori delay specifi nel caso questi fossero non NaN

,ARR_DELAY,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
15,27.0,0.0,27.0,0.0,0.0,0.0
43,27.0,0.0,0.0,27.0,0.0,0.0
45,15.0,15.0,0.0,0.0,0.0,0.0
57,32.0,0.0,0.0,26.0,6.0,0.0
69,27.0,0.0,0.0,27.0,0.0,0.0
...,...,...,...,...,...,...
6429310,20.0,0.0,20.0,0.0,0.0,0.0
6429328,24.0,0.0,0.0,24.0,0.0,0.0
6429329,117.0,117.0,0.0,0.0,0.0,0.0
6429331,91.0,91.0,0.0,0.0,0.0,0.0
6429335,15.0,0.0,0.0,15.0,0.0,0.0

In [65]:
delay_rows_with_nan = df[df[delay_columns].isna().any(axis=1)]

# Ci sono riche che hanno ARR
if delay_rows_with_nan[delay_columns].isna().all(axis=1).all():
    # Verifica se ci sono sia valori positivi che negativi in ARR_DELAY
    positive_arr_delay = (delay_rows_with_nan['ARR_DELAY'] > 0).any()
    negative_arr_delay = (delay_rows_with_nan['ARR_DELAY'] < 0).any()

    if positive_arr_delay and negative_arr_delay:
        # ci sono righe che hanno tutti nan in delay specifici ed hanno sia arr_delay positivi che positivi
        print("Ci sono righe che hanno tutti nan in delay specifici ed hanno sia arr_delay negativi che positivi")

ci sono righe che hanno tutti nan in delay specifici ed hanno sia arr_delay negativi che positivi

In [15]:
# Stampa e elimina le colonne
df = df.drop(columns='Unnamed: 27')

KeyError: "['Unnamed: 27'] not found in axis"

### Analisi su cancelled e diverted

In [30]:
# Calcola la percentuale di 0 e 1 per le colonne "diverted" e "canceled"
percentuali = df[['DIVERTED', 'CANCELLED']].apply(lambda x: x.value_counts(normalize=True) * 100)
print(percentuali)

      DIVERTED  CANCELLED
0.0  99.763541  98.419011
1.0   0.236459   1.580989

In [66]:
# Filtra le righe dove "CANCELLED" Ã¨ 1 e visualizza solo la colonna "CANCELLATION_CODE"
righe_canceled_1 = df.loc[df['CANCELLED'] == 1, 'CANCELLATION_CODE']


# Verifica se ci sono valori NaN nella colonna
if righe_canceled_1.isna().any():
    print("\nCi sono valori NaN nella colonna 'CANCELLATION_CODE' nelle righe dei voli cancellati, quindi che hanno CANCELED pari a 1.0")
else:
    print("\nTutti i valori nella colonna 'CANCELLATION_CODE' sono non NaN nelle righe dei voli cancellati, quindi che hanno CANCELED pari a 1.0.")

print("\nRighe con canceled = 1:")
righe_canceled_1

# Visualizza la frequenza di ciascun valore nella colonna "CANCELLATION_CODE"
print("\nValori unici nella colonna 'CANCELLATION_CODE' con la loro frequenza:")
righe_canceled_1.value_counts()

# A	Carrier	
# B	Weather	
# C	National Air System	
# D	Security

Tutti i valori nella colonna 'CANCELLATION_CODE' sono non NaN nelle righe dei voli cancellati, quindi che hanno CANCELED pari a 1.0.

Righe con canceled = 1:

Valori unici nella colonna 'CANCELLATION_CODE' con la loro frequenza:

CANCELLATION_CODE
B    36651
A    35568
C    14799
D       20
Name: count, dtype: int64

In [ ]:
# SOSTITUIRE CANCELLATION_CODE CON CANCELLATION_REASON

In [31]:
righe_canceled_2 = df.loc[df['CANCELLED'] == 0, 'CANCELLATION_CODE']

# Verifica se tutti i valori sono NaN
if righe_canceled_2.isna().all():
    print("\nTutti i valori nella colonna 'CANCELLATION_CODE' sono NaN nelle righe dei voli NON cancellati, quindi che hanno CANCELED pari a 0.0.")
else:
    print("\nNon tutti i valori nella colonna 'CANCELLATION_CODE' sono NaN nelle righe dei voli NON cancellati, quindi che hanno CANCELED pari a 0.0.")

print("\nRighe con canceled = 2:")
righe_canceled_2

Tutti i valori nella colonna 'CANCELLATION_CODE' sono NaN nelle righe dei voli NON cancellati.

Righe con canceled = 2:

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
          ...
6429333    NaN
6429334    NaN
6429335    NaN
6429336    NaN
6429337    NaN
Name: CANCELLATION_CODE, Length: 6342300, dtype: object

In [10]:
# Filtra le righe dove "diverted" Ã¨ 1
righe_diverted_1 = df[df['DIVERTED'] == 1]

# Stampa o visualizza i risultati
print("Righe con diverted = 1:")
righe_diverted_1.head()

Righe con diverted = 1:

,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN,DEST,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,TAXI_OUT,WHEELS_OFF,...,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,Unnamed: 27
661,2009-01-01,XE,2980,IAH,TYS,1315,1312.0,-3.0,8.0,1320.0,...,122.0,NaN,NaN,772.0,NaN,NaN,NaN,NaN,NaN,NaN
818,2009-01-01,YV,2637,CLT,BHM,2230,2315.0,45.0,8.0,2323.0,...,85.0,NaN,NaN,351.0,NaN,NaN,NaN,NaN,NaN,NaN
1936,2009-01-01,OO,4490,MCI,ATL,1520,1523.0,3.0,11.0,1534.0,...,125.0,NaN,NaN,692.0,NaN,NaN,NaN,NaN,NaN,NaN
1994,2009-01-01,OO,4665,SLC,ACV,1115,1112.0,-3.0,16.0,1128.0,...,115.0,NaN,NaN,635.0,NaN,NaN,NaN,NaN,NaN,NaN
2192,2009-01-01,OO,4878,SLC,BTM,1059,1053.0,-6.0,15.0,1108.0,...,81.0,NaN,NaN,357.0,NaN,NaN,NaN,NaN,NaN,NaN